# Generated by Django 5.1.2 on 2024-10-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='online_review',
            new_name='online_rating',
        ),
        migrations.AddField(
            model_name='product',
            name='amazonreviews',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='flipkartreviews',
            field=models.JSONField(default=list),
        ),
    ]
