# Generated by Django 5.1.2 on 2024-10-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='approvedscore',
            field=models.IntegerField(default=0),
        ),
    ]
